### ISSUE TITLE
Breaks some of the layout

### ISSUE THREAD

**Issue by neoOpus** [foyer-work/ooogle-it#1]
![image](https://user-images.githubusercontent.com/1388336/205906667-e35c8a8f-0f44-4c45-a943-0026c89d9537.png)

**Comment by siddsax** [comment]
Thanks @neoOpus, Adding a copy button is a good idea while fixing the cropping + icon issues. We'll fix that with a patch.

**Comment by neoOpus** [comment]
Hid Sid,

Here is some few enhancement requests, please let me know if you don't find them useful

![image](https://user-images.githubusercontent.com/1388336/206268765-0f0a5e34-98fc-4c58-a411-ba015a727816.png)

**Comment by siddsax** [comment]
@neoOpus , a new version is out on the chrome web-store with some of the improvements you have mentioned. Do checkout! We'll push it here after some cleaning.

**Comment by neoOpus** [comment]
Hi, I've been testing the new version since it was released :) here are some feedbacks, many of them are obvious and you probably thought already about them... I see that you are also working on an option page which is great and I hope that it will allow the customization of different aspects of the layout and design... I have some more case scenarios where it breaks the layout that I can suggest if you are willing to work on them (even if not immediately) so the placement becomes consistent with every search

Thank you

![image](https://user-images.githubusercontent.com/1388336/206841410-6b24ae96-488b-4540-b888-61d70c467386.png)

**Comment by siddsax** [comment]
Thanks @neoOpus for testing it out and give your detailed feedback! Some really nice UX changes and yes the mike icon issue which we missed. We'll add some of these in the next version :)
