### ISSUE TITLE
You have exceeded your quota for some time. Please try later or try it from some other website

### ISSUE THREAD

**Issue by Voight13** [foyer-work/ooogle-it#10]
Getting this response from Merlin. You have exceeded your quota for some time. Please try later or try it from some other website. On your website it is stated, there is no daily data limits, but I get this error.

**Comment by siddsax** [comment]
Hey @Voight13. Its a free extension but on the backend we have been bearing the cost for the API calls :). So to keep the same in check we have imposed some limits. We are working on using a user's chatGPT account directly so as to remove such limits.

**Comment by Voight13** [comment]
> Hey @Voight13. Its a free extension but on the backend we have been bearing the cost for the API calls :). So to keep the same in check we have imposed some limits. We are working on using a user's chatGPT account directly so as to remove such limits.

Is there any way how to remove this limitations currently?

**Comment by siddsax** [comment]
Not currently, though we'll be pushing an update in couple days to help with that.

**Comment by Voight13** [comment]
BTW your tool is amazing! Kepp the work up! Thank you.
