### ISSUE TITLE
You have exceeded your quota for some time. Please try later or try it from some other website

### ISSUE THREAD

**Issue by KevinVuk2** [foyer-work/ooogle-it#12]
I understand the limits thing but can you specify more? I need numbers like when can I continue using it and how many attempts per quota

Great extension btw, so much potential. Keep up the good work.

**Comment by siddsax** [comment]
Thanks @N0rm1ek2 for checking us out. We have kept the limits to 20 requests per hour as we are bearing the API costs on our end. Tho we are working on using chatGPT directly on user's end to lift this limit.

**Comment by shanelindsay** [comment]
It is a nicely coded extension but not useable for me due to limit restrictions. I suggest that you allow the user to input OpenAI API key to allow the user's own unlimited use and no cost to you.

**Comment by scottybo** [comment]
Hi guys, was just getting into the swing of using Merlin and got hit with this message.

I'd be happy to pay to lift the restrictions.

**Comment by siddsax** [comment]
Great to hear @scottybo that you are enjoying using it. We'll be launching in few day with a version to help remove the limits. Hope you can bear with us for the time being :).

**Comment by scottybo** [comment]
@siddsax thank you - please ping me here when it's ready!

**Comment by kslinh** [comment]
I love Merlin, pls ping me here

**Comment by siddsax** [comment]
@scottybo @kslinh, we have launched the paid plan with much higher requests possible. Hope you folks can enjoy as many queries you would like :)
