### ISSUE TITLE
Merlin fails to work on commoncog.com site

### ISSUE THREAD

**Issue by shrix** [foyer-work/ooogle-it#15]
Merlin doesn't seem to work on this particular site ... https://commoncog.com/cash-flow-games/

**Comment by siddsax** [comment]
Thanks @shrix , I am not able to recreate it with the latest version in production. Can you please check to see if its v6.1.0 on your end too? Its available under chrome://extensions and find merlin. Would be great if you can reproduce the error and mention what exactly it is that is not working, or if the command bar is not opening.

**Comment by shrix** [comment]
Not sure if it was due to the transition. Earlier it was on Cmd+G and now supports Cmd+M shortcut. Today it was ok. Thx.
