### ISSUE TITLE
We can provide for free live and up to date financial data. 

### ISSUE THREAD

**Issue by MinaTadrus** [foyer-work/ooogle-it#16]
Give Merlin access to financial data. Happy to share it for free including Open High Low and Close prices of hundreds of assets.

**Comment by siddsax** [comment]
Hey @MinaTadrus sounds interesting. Is there a specific use case/scope you have in mind with the financial data?

**Comment by siddsax** [comment]
Hey @MinaTadrus, closing the issue for now if you don't have a particular use case for now. If you do then feel free to reopen the issue.
