### ISSUE TITLE
Not working when i press "add to chrome" 

### ISSUE THREAD

**Issue by Chimoji** [foyer-work/ooogle-it#17]
Hey everyone!

I tried to press the "add to chrome" button for the Merlin extension, but unfortunately nothing happened and I can't seem to get it to work. If anyone has any suggestions or solutions for this issue, please let me know. I really want to start using this extension, so any help would be greatly appreciated.

Thanks in advance!

**Comment by Patrikkk** [comment]
Same here. I authenticate and log in to my google account when the popup comes up - after I click the "get for chrome" button. THen the windows disappear. Nothing happens, I cant get the extension. Up to date chrome version. On windows 10.

**Comment by AhmedeMushrif** [comment]
Same here, windows 11 up-to-date, tried it on Firefox and it worked just fine.

**Comment by missblacktea** [comment]
You can search Merlin in Ghrome web store and install this extension.

**Comment by AhmedeMushrif** [comment]
It worked! Thanks a lot!

**Comment by Chimoji** [comment]
I fixed it by just looking for the extension in the chome extension store.

Op wo 4 jan. 2023 00:01 schreef Patrikkk ***@***.***>:

**Comment by siddsax** [comment]
Thanks for flagging the issue. I think there's some bug in the auth flow. @27lakshay

**Comment by siddsax** [comment]
It was caused by a bad push, we have fixed it from our end so installation flow should be normal now.
