### ISSUE TITLE
New shortcuts: command + m is the default shortcut to minimize window

### ISSUE THREAD

**Issue by AnishDe12020** [foyer-work/ooogle-it#18]
the new shortcut, command + m is the default macOS shortcut to minimize the front window to the dock and hence interferes with Merlin. would be helpful if we could customize the shortcut/it is changed to something else

**Comment by siddsax** [comment]
Hey @AnishDe12020. Yes it can be changed from `chrome://extensions/shortcuts` assuming you are using chrome. Other browsers with redirect with this link. Go to this link and then scroll down to Merlin for the same.

**Comment by AnishDe12020** [comment]
Cool, works
