### ISSUE TITLE
Issue opening with CTRL+M

### ISSUE THREAD

**Issue by jxfriis** [foyer-work/ooogle-it#19]
It used to work when opening Merlin by using CTRL+G but now when it has been changed to CTRL+M, it no longer works.

**Comment by siddsax** [comment]
Hey! Are you facing this issue on Chrome or edge? Thanks

**Comment by jxfriis** [comment]
I'm using edge

Den tor. 5. jan. 2023 kl. 08.55 skrev Siddhartha Saxena <
***@***.***>:

**Comment by siddsax** [comment]
Thanks! It seems there is an issue with edge on windows. We are working on it and will push a Hotfix. Meanwhile you can change the shortcut from `edge://extensions/shortcuts`

**Comment by siddsax** [comment]
Hey @supahx , we have pushed an update that helps you change this from the command bar via a this link. Hope that solves the problem. Closing the issue for now. In case the problem persists, feel free to open the issue.
