### ISSUE TITLE
extension-node isn't using ChatGPT API

### ISSUE THREAD

**Issue by gmchad** [foyer-work/ooogle-it#22]
The ChatGPT API isn't released yet, although there are plenty of unofficial forks i.e [https://github.com/acheong08/ChatGPT](https://github.com/acheong08/ChatGPT)

Are you guys running an unofficial api server under the hood somewhere?

**Comment by siddsax** [comment]
Hey @chadlohrli, we are actually using the text-davinci-003 API from OpenAI. Its the base model powering chatGPT as well. The problem with the unofficial APIs are that they need constant refresh and break at scale due to OpenAI limits.

**Comment by siddsax** [comment]
@chadlohrli closing the issue in case it was cleared
