### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by s2erge** [foyer-work/ooogle-it#24]
The extension does open on google docs but on its main page, when I go to one of my files the merlin does not open!

**Comment by siddsax** [comment]
Hey @s2erge, this should ideally not be happening with the latest version. Just wanted to confirm if you are with the latest version i.e using cmd/ctrl+M for summoning the command bar. Also will be really helpful if you can share the OS + browser you are using.

**Comment by s2erge** [comment]
I'm using the latest version, my OS is Windows 11 & my browser is Microsoft Edge!

**Comment by siddsax** [comment]
Thanks for the info @s2erge ! Yes we know about this issue on windows + edge browser. A quick fix would be if you can go in the shortcut menu `edge://extensions/shortcuts` or open the same page from within the extension and set the `Run merlin on current page` shortcut to anything of your choice then it should open the command bar in google docs.

**Comment by s2erge** [comment]
Thank you for the reply I will try it out and see if it fix!

**Comment by siddsax** [comment]
Hey @s2erge do let me know if that worked for you. Thanks
