### ISSUE TITLE
Do you plan to support Thunderbird?

### ISSUE THREAD

**Issue by PiFlUn** [foyer-work/ooogle-it#26]

**Comment by siddsax** [comment]
Hey @PiFlUn , for supporting thunderbird we'll probably need an OS app I am not wrong. At present we don't have plans to create an OS client. Although we'll for sure look into it if there are other use cases that might be supported via an OS client opposed to a chrome extension.

**Comment by siddsax** [comment]
@PiFlUn Closing the issue as no plans for now
