### ISSUE TITLE
When selecting Text on some websites Merlin blocks features of the website.

### ISSUE THREAD

**Issue by b-dennis101** [foyer-work/ooogle-it#27]
Description of the problem:
I use this website app.genei.io with a notion like text editor. When selection text I normally can modify it, but with this add-on the merlin popup blocks the menu. The blocking isn't visual, but if I now try to click on the text menu, it disappears. Without Merlin, the text menu works fine.
![grafik](https://user-images.githubusercontent.com/122453486/211809127-a14d89ec-6ec2-4955-8227-ac6cdfaa0797.png)
Additionally, it is inconvenient because turning the add-on on and off in Firefox I need to go to the add-on setting. I can't put Merlin in the add-on taskbar.

I hope this can be fixed.

**Comment by siddsax** [comment]
Hey @b-dennis101 , we have actually fixed this issue in chrome, but we are lagging a bit with the updates on firefox. We'll release the update there soon tho.

**Comment by timwessels** [comment]
The Merin-icon that appears when selecting text is generelly disturbing - if ofter overlays other information or functions you need. It would make much more sense to have it in the right-click menu like other extensions. At least, the Merin-icon should be possible to switch it off. Like this, I need to have the whole extension turned off as my default setting.
(commend refers to Firefox-version)

**Comment by siddsax** [comment]
Yup, totally agree. We'll release the firefox version fixing this in couple days.

**Comment by siddsax** [comment]
Hey @b-dennis101 , we have released the new version fixing this. Hope you have fun :)
