### ISSUE TITLE
Merlin takes over CMD+K on Firefox on Mac 

### ISSUE THREAD

**Issue by StanfordAlan** [foyer-work/ooogle-it#28]
First, Merlin is incredibly useful! But I’m having a real issue with it overwriting my most used shortcut in Firefox.

I’m running Merlin in 106.0.1 on MacOS 13.0.1. From Merlin’s documentation, CMD+G is supposed to bring up the modal. It does.

**BUT Cmd+K also brings it up instead of allowing me to access the standard search bar/field. I need that shortcut back.** 

The onboarding page of the website has an area that is supposed to include info about changing shortcuts, but that seems to work on Chrome _only_. There's no icon in Firefox for me.

Also, CMD+M on a Mac minimizes the window by MacOS itself. So, I don’t think it will work.

CMD+K is also used by Firefox for Find Again, so it would be great if the shortcuts were changeable.

Anyway, how can I get Cmd+K working again?

Thank you.

**Comment by siddsax** [comment]
Thanks for checking us out! At the moment it's actually not possible to change shortcuts in firefox for our extension. Our firefox extension is a but behind Chrome. Although we are working on the having version parity b/w Chrome and Firefox. This should be out in 2-3 day. Then you'll be able to change the shortcut easily.

**Comment by siddsax** [comment]
Hey @StanfordAlan, this is now in production. Do let us know if you face any issues.

**Comment by sammcj** [comment]
Now it's taken over the quit hotkey! - https://github.com/foyer-work/Ooogle-it/issues/37
