### ISSUE TITLE
So now it's named Merlin?

### ISSUE THREAD

**Issue by neoOpus** [foyer-work/ooogle-it#3]
I see that you did update this and renamed it but this doesn't reflect on Github repository, is this going to be closed source?

**Comment by siddsax** [comment]
Hey @neoOpus! Yes, we changed the name as it was covering more than google now. Although we are planning to maintain the google related parts here, hence will push that.

**Comment by itwarlock** [comment]
how do I get the old version.

**Comment by siddsax** [comment]
We'll clean up the code and push the same.
