### ISSUE TITLE
Sentry logs in console

### ISSUE THREAD

**Issue by DarkZeus** [foyer-work/ooogle-it#31]
What data is collected by Merlin? Why does it have a connection to the Sentry and can it be disabled? At least I wouldn't want to see these messages in my console since there are a lot of them.
![image](https://user-images.githubusercontent.com/7280260/213276657-ed6dd9e9-cae1-48ae-b325-ce56f42b5b45.png)

**Comment by siddsax** [comment]
Hey @DarkZeus, recently we added sentry to get on top of UI bugs that we were facing. It basically collects data on UI crashes and errors. Though the integration seems to have led to too many logs. We have pushed a version without sentry for now.

**Comment by DarkZeus** [comment]
Thank you much. Issue can be closed.

**Comment by dave986** [comment]
Hello @siddsax! I have to say I am concerned about this logging as well. Good that it is gone. First of all, it is unacceptable for an extension to spam the console, as you probably found yourself. Second, you should collect telemetry only with explicit user approval. I believe it is not just unethical but also illegal, at least in the EU (GDPR). Please do not do it again without user consent, similar to what every other app has - "There is XY error. Do you wish to send debugging data to the developer? OK|Cancel|**Review Report**". 
PS: Thanks for the extension. It is brilliant :)

**Comment by siddsax** [comment]
Yes agreed, for sure it should not be spamming the console. We are working on a version of Privacy Policy with all these things and add that to the chrome webstore.
