### ISSUE TITLE
Error During Onboarding

### ISSUE THREAD

**Issue by jeanofthedead** [foyer-work/ooogle-it#32]
When I attempt to install your plugin for Firefox 109.0 on macOS Venture 13.1, I receive the following error after signing in with my Google account:

`Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.`

**Comment by 27lakshay** [comment]
Thanks for reporting the issue, we'll look into it.

**Comment by 27lakshay** [comment]
Thanks for reporting the issue, we'll look into it.

**Comment by siddsax** [comment]
Hey @jeanofthedead, just wanted to get back. Are you able to install the extension directly from [here](https://addons.mozilla.org/en-US/firefox/addon/merlin-chatgpt-on-browser/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)?

**Comment by siddsax** [comment]
Closed due to lack of activity.
