### ISSUE TITLE
Ratelimit Bypass

### ISSUE THREAD

**Issue by Reginald-Gillespie** [foyer-work/ooogle-it#35]
When I checked the API for security to see if it had any sort of method to prevent botting, I saw it had a userid field. Then I tried a random ID and found that it just ratelimits by userid, it doesn't actually verify that your userid is valid. So I can just provide your api with a random ID per request and make infinite chatgpt calls.

It was fun to hook it up to a discord bot and mess with it but figured you would want to know before someone abuses it and you get charged a ton of money.

**Comment by siddsax** [comment]
Thanks @Reginald-Gillespie for flagging this :). This is a major loophole but even if we use a private-key/public-key based verification, one can use the backend call to just create tokens from there. The solution we'll soon be shipping is google sign-in to prevent such abuse. In the meantime, we can just ask for your goodwill to not abuse it or we'll have to stop the service completely for all the users :( 

Will be happy to know if you have any other good solutions in mind.

**Comment by Reginald-Gillespie** [comment]
I believe you already ratelimit by IP so that's good, but yeah you really do need a login method to actually fix the problem. Google emails are so easy to get, phone verification (and making sure they are cell and not VoIP) might be better. 

I wish OpenAI had an open login api system because their system is pretty good at verification.

**Comment by siddsax** [comment]
We have added google auth. So it will prevent folks from directly abusing the API endpoints. Stopping tries with multiple google auth is not a priority for us now.
