### ISSUE TITLE
Clicking "Submit Bug" on the Merlin website requires an account with Google

### ISSUE THREAD

**Issue by sammcj** [foyer-work/ooogle-it#38]
Click [submit bug](https://merlin.foyer.work/onboarding/) on the website:

![image](https://user-images.githubusercontent.com/862951/215591883-c71dbc3c-c8fd-4e33-97e8-5e3f2d8a8cdc.png)

Takes you to a page that seems to require an account with Google:

![image](https://user-images.githubusercontent.com/862951/215591823-98ea81f4-5c03-4866-884e-f79d8d41b964.png)

Users shouldn't have to sign up with Google to log a bug for a Firefox extension.

**Comment by siddsax** [comment]
Hey @sammcj we have added mainly so that we can reach out and solve the issue for customers on their own end.
