### ISSUE TITLE
'UNAUTHORIZED' Error When Copying Text

### ISSUE THREAD

**Issue by ghost** [foyer-work/ooogle-it#41]
When doing the keyboard shortcut, when attempting to write a prompt, I am not allowed, and it says 'UNAUTHORIZED' without any other information - rebooted browser and computer to no avail. <img width="678" alt="Screenshot 2023-02-07 at 2 25 19 PM" src="https://user-images.githubusercontent.com/124733596/217357510-eb6ea098-9bd8-4551-8fc1-2bbb18ae055f.png">

**Comment by siddsax** [comment]
Thanks for flagging! We are working on this bug fix. In the meantime, you can try logging out from the extension via the popup and then logging back in.

**Comment by siddsax** [comment]
Hey @fbm4749, in the latest build, this error should be handled. Closing the issue for now, though please reopen in case its persisting for you.
