### ISSUE TITLE
How to disable the control button

### ISSUE THREAD

**Issue by feelfetch** [foyer-work/ooogle-it#5]
Super cute, but annoying :)

**Comment by siddsax** [comment]
Yup, we are working on an update to have an option to disable it.

**Comment by siddsax** [comment]
Hey @feelfetch. We have released this feature in the latest update and now it automatically disappears after few seconds too. Do let us know if you face any issues.

**Comment by feelfetch** [comment]
Awesome! Re-installed. Thank you!!
