### ISSUE TITLE
How to customize shortcut?

### ISSUE THREAD

**Issue by shigasia** [foyer-work/ooogle-it#6]
in my case, cmd + g and cmd + k can work, but it is conflicted with my current shortcut workflows, but your setting page have nothing right there, can you tell me how to modify this?

**Comment by 27lakshay** [comment]
We are working on adding a settings page, with customizability options and doing critical bug fixes, making the extension more stable.
Thanks for the suggestion, we'll if we can add this in the settings page.

**Comment by siddsax** [comment]
Hi! So now that we are using a shortcut via chrome extension option. It can be altered from `edge://extensions/shortcuts`. We'll add a link to this page in the settings menu too. Also hopefully cmd/ctrl+M is not conflicting with most of the workflow.
