### ISSUE TITLE
Our Servers Are Running Too Hot! Please Check Back After Some Time.

### ISSUE THREAD

**Issue by Willlance** [foyer-work/ooogle-it#7]
When all the transfers will be done?

**Comment by siddsax** [comment]
Yes we are working on the issue. Its mainly due to the limitations impoes by Open AI's API. We are working on a work-around. Will post an update soon.

**Comment by siddsax** [comment]
It should be working now. Thanks for the patience :)

**Comment by Willlance** [comment]
> It should be working now. Thanks for the patience :)

Thank you <3
