### ISSUE TITLE
Merlin is casting its spell via OpenAI GPT

### ISSUE THREAD

**Issue by savchenkohost** [foyer-work/ooogle-it#9]
Hello, for any requests Merlin answers is: "Merlin is casting its spell via OpenAI GPT".

**Comment by siddsax** [comment]
Hey @savchenkohost , this generally happens when requests fail for some reason. We are working on better error handling which reflects the same to the user. Though right now the services seem to be up. Let me know if its happening now.

**Comment by savchenkohost** [comment]
Thanks, already working ok!
I also offer you an idea to add Merlin chat directly on your official website.

**Comment by siddsax** [comment]
That sounds pretty cool. Yeah, I also think we should do that!
